python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=0 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=1 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=2 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=3 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=4 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=5 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=6 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=7 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=8 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=9 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=10 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=11 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=12 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=13 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=14 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=15 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=16 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=17 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=18 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=19 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=20 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=21 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=22 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=23 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=24 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=25 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=26 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=27 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=28 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=29 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=30 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=31 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=32 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=33 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=34 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=35 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=36 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=37 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=38 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=39 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=40 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=41 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=42 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=43 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=44 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=45 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=46 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=47 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=48 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=49 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=50 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=51 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=52 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=53 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=54 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=55 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=56 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=57 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=58 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=59 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=60 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=61 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=62 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=63 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=64 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=65 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=66 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=67 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=68 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=69 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=70 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=71 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=72 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=73 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=74 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=75 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=76 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=77 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=78 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=79 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=80 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=81 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=82 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=83 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=84 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=85 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=86 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=87 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=88 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=89 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=90 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=91 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=92 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=93 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=94 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=95 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=96 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=97 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=98 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=99 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=100 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=101 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=102 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=103 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=104 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=105 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=106 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=107 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=108 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=109 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=110 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=111 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=112 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=113 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=114 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=115 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=116 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=117 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=118 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=119 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=120 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=121 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=122 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=123 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=124 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=125 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=126 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=127 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=128 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=129 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=130 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=131 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=132 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=133 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=134 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=135 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=136 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=137 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=138 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=139 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=140 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=141 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=142 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=143 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=144 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=145 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=146 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=147 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=148 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=149 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=150 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=151 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=152 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=153 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=154 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=155 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=156 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=157 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=158 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=159 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=160 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=161 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=162 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=163 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=164 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=165 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=166 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=167 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=168 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=169 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=170 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=171 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=172 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=173 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=174 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=175 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=176 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=177 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=178 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=179 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=180 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=181 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=182 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=183 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=184 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=185 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=186 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=187 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=188 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=189 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=190 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=191 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=192 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=193 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=194 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=195 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=196 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=197 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=198 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
python3 /home/hj14/pytorch-cifar/main.py  --resume --depth=18 --ckpt=199 --train=0 | tee -a /shared/hj14/tiny-imagenet/sparsity-18.log
